# Generated by Django 5.0.8 on 2024-08-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('about_me', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT'), ('NON-IT', 'NON-IT'), ('mobile phone', 'mobile phone')], max_length=100)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
